version: '3.8'
services:
  postgres:
    container_name: "picture-room-postgres-test"
    networks:
      - picture-room-test
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: picture-room_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=500'
    volumes:
      - ./pg-data-test:/var/lib/postgresql/data
  api:
    container_name: "picture-room-api-test"
    networks:
      - picture-room-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 4000:4000
    depends_on:
      - postgres
    environment:
      PORT: 4000

volumes:
  pg-data-test:

networks:
  picture-room-test:

