FROM golang:1.15-alpine

RUN apk add --no-cache openssl git

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN go get github.com/cespare/reflex

WORKDIR /app

EXPOSE 4000

CMD ["dockerize", "-wait", "tcp://postgres:5432", "-timeout", "1m", "reflex", "-c", "reflex.conf"]
